language: python

python:
  - "2.7"

install:
  - pip install -q Django==1.8.4
  - pip install MySQL-python
  - pip install django-formtools
  - pip install pytz
  
before_script:
  - "mysql -u root -e 'create database IF NOT EXISTS slp_georgias_test;'"
  - "mysql -u root -e \"grant all on slp_georgias_test.* to 'georgias';\""
  
script: 
  - cd georgias; python manage.py makemigrations; python manage.py migrate; python manage.py test
  
sudo : false

notifications:
  email: false

